extern crate core;

mod animation;
mod background_noise;
mod board_dimensions;
mod camera;
mod capman;
pub mod common;
mod constants;
mod debug;
mod edibles;
mod game_assets;
mod game_over_screen;
mod ghost_corners;
mod ghost_house;
mod ghost_house_gate;
mod ghosts;
mod interactions;
mod level;
mod life_cycle;
mod lives;
pub mod map;
mod random;
mod ready_screen;
mod score;
mod specs_per_level;
mod speed;
mod sprite_sheet;
mod tunnels;
mod walls;
